export const serviceUrls = {
  signup: '/user/signup',
  video: '/role/videolink/',
  rooms: '/room/user-rooms',
  filteredUsersList: '/user/getalluser?search=',
  deleteRole: '/role/deleterole/',
  getAllUsers: '/user/getalluser',
  getAllVideo: '/role/userVideo',
  deleteVideo: '/role/deletevideo',
  registerSpectator: '/role/spectator/Register',
  updateRole: 'role/updaterole/',
  getVideoById: '/role/getvideo',
  roomsRelatedUrl: '/room/rooms',
  filteredRoomsList: '/room/rooms?search=',
  allRooms: 'room/rooms',
  regRooms: 'team/register-room', //registered rooms
  joinMatch: 'payment/create-payment',
  updateUserDetails: '/user/updateuser',
  sendInvite: '/user/send-invite',
  forgetPassword: 'user/forget-password',
  login: 'user/login',
  resetPassword: 'user/reset-password?token=',
  videoUpdateService: 'role/updatevideo/',
  getRoomTeams: '/room/getTeam/',
  winnerGetPlayer: '/winners/get-players/',
  winnerPlayerUpdate: '/winners/players/',
  getAllRoom: 'room/user-rooms',
  deletefriend: '/team/remove-team-mate',
  inviteMail: '/user/send-invite',
  globalusers: '/user/getalluser',
  getAllFriends: '/team/user-teams',
};
