export const serviceUrls = {
  signup: '/user/signup',
  video: '/role/videolink/',
  rooms: '/room/user-rooms',
  filteredUsersList: '/user/getalluser?search=',
  deleteRole: '/role/deleterole/',
  getAllUsers: '/user/getalluser',
  getAllVideo: '/role/userVideo',
  deleteVideo: '/role/deletevideo',
  registerSpectator: '/role/spectator/Register',
  updateRole: 'role/updaterole/',
  updateVideo: '/role/getvideo',
  roomsRelatedUrl: '/room/rooms',
  filteredRoomsList: '/room/rooms?search=',
  allRooms: 'room/rooms',
  regRooms: 'team/register-room', //registered rooms
  joinMatch: 'payment/create-payment',
  updateUserDetails: '/user/updateuser',
  sendInvite: '/user/send-invite',
  forgetPassword: 'user/forget-password',
  login: 'user/login',
  resetPassword: 'user/reset-password?token=',
  videoUpdateService: 'role/updatevideo/',
};
