
"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Sidebar from '@/Components/SideBar/Sidebar'
import {
    FaTh,
    FaUserAlt,
    FaRegChartBar,
    FaCommentAlt,
  } from "react-icons/fa";
const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }
const dynamicMenuItems = [
    {
      path: "/userDashboard/tournament",
      name: "Tournament",
      icon: <FaTh />,
    },
    {
      path: "/userDashboard/transactions",
      name: "Transactions",
      icon: <FaUserAlt />,
    },
    {
      path: "/userDashboard/friends",
      name: "Friends",
      icon: <FaRegChartBar />,
    },
    {
      path: "/userDashboard/videos",
      name: "Videos",
      icon: <FaCommentAlt />,
    },
    {
      path: "/userDashboard/kyc",
      name: "KYC",
      icon: <FaCommentAlt />,
    }
];
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div>
 <Sidebar menuItem={dynamicMenuItems} /> 
      {children}
      </div>
    )
}
