
"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Sidebar from '@/Components/SideBar/Sidebar'
import {
    FaTh,
    FaUserAlt,
    FaRegChartBar,
    FaCommentAlt,
  } from "react-icons/fa";
const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }
const dynamicMenuItems = [
    {
      path: "/adminDashboard/room",
      name: "Room",
      icon: <FaTh />,
    },
    {
      path: "/adminDashboard/spectator",
      name: "Specatator",
      icon: <FaUserAlt />,
    },
    {
      path: "/adminDashboard/users",
      name: "Users",
      icon: <FaRegChartBar />,
    },
    {
      path: "/adminDashboard/teams",
      name: "Teams",
      icon: <FaCommentAlt />,
    }
];
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div>
 <Sidebar menuItem={dynamicMenuItems} /> 
      {children}
      </div>
    )
}
